## Libraries importieren

In [5]:
import pandas as pd

## Daten einlesen

Die Daten sind als csv-Daten im gleichen Ordner abgelegt, versehen mit dem Datum wann die Seite gescrapt wurde.

In [13]:
path = "anzahl_jobs_04-11-2018.csv"

with open(path) as f:
    dateiinhalt = f.read()

In [14]:
print(dateiinhalt)

# @ THIERRY: Hier fängt mein Problem an. ich will eine tabelle. eine Variable sind Berufsbezeichnungen, das andere das Resultat
# So wie das daher kommt komme ich unten nich weiter! zB alle Resultate zusammenzählen.

Abdichter/in EFZ,Abdichtungspraktiker/in EBA,Agrarpraktiker/in EBA,Anlagen- und Apparatebauer/in EFZ,Anlagenführer/in EFZ,Architekturmodellbauer/in EFZ,Assistent/in Gesundheit und Soziales EBA,Augenoptiker/in EFZ,Automatiker/in EFZ,Automatikmonteur/in EFZ,Automobil-Assistent/in EBA,Automobil-Fachmann/-frau EFZ,Automobil-Mechatroniker/in EFZ,Bäcker/in-Konditor/in-Confiseur/in EBA,Bäcker/in-Konditor/in-Confiseur/in EFZ,Baumaschinenmechaniker/in EFZ,Baupraktiker/in EBA,Bauwerktrenner/in EFZ,Bekleidungsgestalter/in EFZ,Bekleidungsnäher/in EBA,Betonwerker/in EFZ,Boden-Parkettleger/in EFZ,Bootbauer/in EFZ,Bootfachwart/in EFZ,Buchhändler/in EFZ,Büchsenmacher/in EFZ,Bühnentänzer/in EFZ,Büroassistent/in EBA,Carrosserielackierer/in EFZ,Carrosseriespengler/in EFZ,Chemie- und Pharmapraktiker/in EBA,Chemie- und Pharmatechnologe/-login EFZ,Coiffeur/-euse EBA,Coiffeur/-euse EFZ,Dachdecker/in EFZ,Dachdeckerpraktiker/in EBA,Dekorationsnäher/in EBA,Dentalassistent/in EFZ,Detailhandelsassistent/in EBA,"Detailhandelsfachmann/-frau EFZ, Schwerpunkt Beratung","Detailhandelsfachmann/-frau EFZ, Schwerpunkt Bewirtschaftung",Diätkoch/-köchin EFZ,Drogist/in EFZ,"Edelstein-/Diamantenschleifer/in (EFZ, Kt. Regl. TI)",Elektroinstallateur/in EFZ,Elektroniker/in EFZ,Elektroplaner/in EFZ,Entwässerungspraktiker/in EBA,Entwässerungstechnologe/-login EFZ,Fachmann/-frau Betreuung EFZ,Fachmann/-frau Betriebsunterhalt EFZ,Fachmann/-frau Bewegungs- und Gesundheitsförderung EFZ,Fachmann/-frau Gesundheit EFZ,Fachmann/-frau Hauswirtschaft EFZ,Fachmann/-frau Information und Dokumentation EFZ,Fachmann/-frau Kundendialog EFZ,Fachmann/-frau Leder und Textil EFZ,Fachmann/-frau öffentlicher Verkehr EFZ,Fachmann/-frau Textilpflege EFZ,Fahrradmechaniker/in EFZ,Fahrzeugschlosser/in EFZ,Fassadenbauer/in EFZ,Fassadenbaupraktiker/in EBA,Feinwerkoptiker/in EFZ,Fleischfachassistent/in EBA,Fleischfachmann/-frau EFZ,Flexodrucker/in EFZ,Florist/in EBA,Florist/in EFZ,Formenbauer/in EFZ,Formenpraktiker/in EBA,Forstpraktiker/in EBA,Forstwart/in EFZ,Fotofachmann/-frau EFZ,Fotograf/in EFZ,Gärtner/in EBA,Gärtner/in EFZ,Gästeempfangsfachmann/-frau HGA EFZ (Kt. Verordnung VS),Gebäudereiniger/in EBA,Gebäudereiniger/in EFZ,Gebäudetechnikplaner/in Heizung EFZ,Gebäudetechnikplaner/in Lüftung EFZ,Gebäudetechnikplaner/in Sanitär EFZ,Geflügelfachmann/-frau EFZ,Geigenbauer/in EFZ,Gemüsegärtner/in EFZ,Geomatiker/in EFZ,Gerüstbauer/in EFZ,Gerüstbaupraktiker/in EBA,Gestalter/in Werbetechnik EFZ,Gewebegestalter/in EFZ,Gipser/in-Trockenbauer/in EFZ,Gipserpraktiker/in EBA,"Glasapparatebauer/in (EFZ, Kt. Regl. BS)",Glaser/in EFZ,Glasmaler/in EFZ,Gleisbauer/in EFZ,Gleisbaupraktiker/in EBA,Goldschmied/in EFZ,Grafiker/in EFZ,Graveur/in EFZ,Grundbauer/in EFZ,Grundbaupraktiker/in EBA,Gussformer/in EFZ,Gusstechnologe/-login EFZ,Haustechnikpraktiker/in EBA,Hauswirtschaftspraktiker/in EBA,Heizungsinstallateur/in EFZ,Holzbearbeiter/in EBA,Holzbildhauer/in EFZ,Holzhandwerker/in EFZ,Hörsystemakustiker/in EFZ,Hotelfachmann/-frau EFZ,Hotel-Kommunikationsfachmann/-frau EFZ,Hotellerieangestellte/r EBA,Hufschmied/in EFZ,ICT-Fachmann/-frau EFZ,Industrie- und Unterlagsbodenbauer/in EFZ,Industrie- und Unterlagsbodenbaupraktiker/in EBA,Industriekeramiker/in EFZ,Industrielackierer/in EFZ,Industriepolsterer/-polsterin EFZ,Informatiker/in EFZ,Innendekorateur/in (EFZ),Interactive Media Designer EFZ,Isolierspengler/in EFZ,Kältemontage-Praktiker/in EBA,Kältesystem-Monteur/in EFZ,Kältesystem-Planer/in EFZ,Kaminfeger/in EFZ,"Kaufmann/-frau EFZ, Basis-Grundbildung","Kaufmann/-frau EFZ, erw. Grundbildung",Keramiker/in EFZ,Kleinmotorrad- und Fahrradmechaniker/in EFZ,Koch/Köchin EFZ,Konstrukteur/in EFZ,Korb- und Flechtwerkgestalter/in EFZ,Kosmetiker/in EFZ,Küchenangestellte/r EBA,Küfer/in EFZ,Kunststofftechnologe/-login EFZ,Kunststoffverarbeiter/in EBA,Laborant/in EFZ,Lackierassistent/in EBA,Landmaschinenmechaniker/in EFZ,Landwirt/in EFZ,Lebensmittelpraktiker/in EBA,Lebensmitteltechnologe/-login EFZ,Logistiker/in EBA,Logistiker/in EFZ,Lüftungsanlagenbauer/in EFZ,Maler/in EFZ,Malerpraktiker/in EBA,Marmorist/in EFZ,Matrose/Matrosin der Binnenschifffahrt EFZ,Maurer/in EFZ,Mechanikpraktiker/in EBA,Mediamatiker/in EFZ,Medientechnologe/-login EFZ,Medizinische/r Praxisassistent/in EFZ,Medizinproduktetechnologe/-login EFZ,Messerschmied/in EFZ,Metallbauer/in EFZ,Metallbaukonstrukteur/in EFZ,Metallbaupraktiker/in EBA,Mikromechaniker/in EFZ,Mikrozeichner/in EFZ,Milchpraktiker/in EBA,Milchtechnologe/-login EFZ,Montage-Elektriker/in EFZ,Motorgerätemechaniker/in EFZ,Motorradmechaniker/in EFZ,Müller/in EFZ,Multimediaelektroniker/in EFZ,Musikinstrumentenbauer/in EFZ,Netzelektriker/in EFZ,Oberflächenbeschichter/in EFZ,Oberflächenpraktiker/in EBA,Oberflächenveredler/in Uhren und Schmuck EFZ,Obstfachmann/-frau EFZ,Ofenbauer/in EFZ,Orthopädieschuhmacher/in EFZ,Orthopädist/in EFZ,Papiertechnologe/-login EFZ,Pferdefachmann/-frau EFZ,Pferdewart/in EBA,Pflästerer/Pflästerin EFZ,Pharma-Assistent/in EFZ,Physiklaborant/in EFZ,Plattenleger/in EFZ,Plattenlegerpraktiker/in EBA,Podologe/-login EFZ,Polisseur/-euse EBA,Polydesigner/in 3D EFZ,Polygraf/in EFZ,Polymechaniker/in EFZ,Printmedienpraktiker/in EBA,Printmedienverarbeiter/in EFZ,Produktionsmechaniker/in EFZ,Recyclist/in EFZ,Reifenpraktiker/in EBA,Restaurationsangestellte/r EBA,Restaurationsfachmann/-frau EFZ,Säger/in Holzindustrie EFZ,Sanitärinstallateur/in EFZ,Schreiner/in EFZ,Schreinerpraktiker/in EBA,Schuhmacher/in EFZ,Seilbahner/in EBA,Seilbahn-Mechatroniker/in EFZ,Spengler/in EFZ,Steinbildhauer/in EFZ,Steinmetz/in EFZ,Steinsetzer/in EBA,Steinwerker/in EFZ,Storenmontagepraktiker/in EBA,Storenmonteur/in EFZ,Strassenbauer/in EFZ,Strassenbaupraktiker/in EBA,Strassentransportfachmann/-frau EFZ,Strassentransportpraktiker/in EBA,Systemgastronomiefachmann/-frau EFZ,Telematiker/in EFZ,Textilpraktiker/in EBA,Textiltechnologe/-login EFZ,Theatermaler/in EFZ,Tiermedizinische/r Praxisassistent/in EFZ,Tierpfleger/in EFZ,Uhrenarbeiter/in EBA,Uhrmacher/in EFZ,Uhrmacher/in Produktion EFZ,Unterhaltspraktiker/in EBA,Veranstaltungsfachmann/-frau EFZ,Vergolder/in-Einrahmer/in EFZ,Verpackungstechnologe/-login EFZ,Weintechnologe/-login EFZ,Winzer/in EFZ,Wohntextilgestalter/in EFZ,Zahntechniker/in EFZ,Zeichner/in EFZ,Zimmermann/Zimmerin EFZ
135,44,57,209,137,0,478,122,365,103,89,607,558,74,338,70,96,20,134,10,18,136,6,16,40,1,0,115,170,149,16,106,138,775,168,46,2,452,963,2116,1463,75,77,0,1534,204,95,4,17,787,612,32,1903,416,24,72,7,33,22,57,41,50,16,9,60,167,12,2,86,6,1,1,125,24,3,146,587,0,20,68,120,79,102,7,0,19,61,49,11,35,1,111,33,2,25,0,49,4,8,45,2,26,10,8,8,226,132,422,94,6,1,10,244,56,30,3,64,12,2,2,23,6,836,21,50,9,7,47,5,67,655,4622,1,11,1142,289,1,51,159,0,92,25,278,36,75,525,22,86,108,1102,72,393,45,1,2,608,81,131,92,148,10,0,343,81,65,27,10,29,129,718,20,16,16,54,4,160,26,16,5,27,19,10,2,7,68,35,4,285,19,81,17,28,1,26,50,1084,8,46,381,34,80,103,524,31,662,618,123,3,8,15,323,2,12,0,7,5,37,261,47,203,21,89,44,6,20,0,23,20,26,46,21,50,12,1,16,18,39,11,14,397,431

In [10]:
# csv-Datei hat keine Kopfzeile. Diese Info muss beim Öffnen mitgegeben werden

df = pd.read_csv(path, header=None)

In [11]:
df

,0,1,2,3,4,5,6,7,8,9,...,231,232,233,234,235,236,237,238,239,240
0,Abdichter/in EFZ,Abdichtungspraktiker/in EBA,Agrarpraktiker/in EBA,Anlagen- und Apparatebauer/in EFZ,Anlagenführer/in EFZ,Architekturmodellbauer/in EFZ,Assistent/in Gesundheit und Soziales EBA,Augenoptiker/in EFZ,Automatiker/in EFZ,Automatikmonteur/in EFZ,...,Unterhaltspraktiker/in EBA,Veranstaltungsfachmann/-frau EFZ,Vergolder/in-Einrahmer/in EFZ,Verpackungstechnologe/-login EFZ,Weintechnologe/-login EFZ,Winzer/in EFZ,Wohntextilgestalter/in EFZ,Zahntechniker/in EFZ,Zeichner/in EFZ,Zimmermann/Zimmerin EFZ
1,135,44,57,209,137,0,478,122,365,103,...,50,12,1,16,18,39,11,14,397,431

In [19]:
pd.melt(df)

     variable                                      value
0           0                           Abdichter/in EFZ
1           0                                        135
2           1                Abdichtungspraktiker/in EBA
3           1                                         44
4           2                      Agrarpraktiker/in EBA
5           2                                         57
6           3          Anlagen- und Apparatebauer/in EFZ
7           3                                        209
8           4                       Anlagenführer/in EFZ
9           4                                        137
10          5              Architekturmodellbauer/in EFZ
11          5                                          0
12          6   Assistent/in Gesundheit und Soziales EBA
13          6                                        478
14          7                        Augenoptiker/in EFZ
15          7                                        122
16          8                         Automatiker/in EFZ
17          8                                        365
18          9                    Automatikmonteur/in EFZ
19          9                                        103
20         10                 Automobil-Assistent/in EBA
21         10                                         89
22         11               Automobil-Fachmann/-frau EFZ
23         11                                        607
24         12             Automobil-Mechatroniker/in EFZ
25         12                                        558
26         13     Bäcker/in-Konditor/in-Confiseur/in EBA
27         13                                         74
28         14     Bäcker/in-Konditor/in-Confiseur/in EFZ
29         14                                        338
..        ...                                        ...
452       226  Tiermedizinische/r Praxisassistent/in EFZ
453       226                                         23
454       227                         Tierpfleger/in EFZ
455       227                                         20
456       228                       Uhrenarbeiter/in EBA
457       228                                         26
458       229                           Uhrmacher/in EFZ
459       229                                         46
460       230                Uhrmacher/in Produktion EFZ
461       230                                         21
462       231                 Unterhaltspraktiker/in EBA
463       231                                         50
464       232           Veranstaltungsfachmann/-frau EFZ
465       232                                         12
466       233              Vergolder/in-Einrahmer/in EFZ
467       233                                          1
468       234           Verpackungstechnologe/-login EFZ
469       234                                         16
470       235                  Weintechnologe/-login EFZ
471       235                                         18
472       236                              Winzer/in EFZ
473       236                                         39
474       237                 Wohntextilgestalter/in EFZ
475       237                                         11
476       238                       Zahntechniker/in EFZ
477       238                                         14
478       239                            Zeichner/in EFZ
479       239                                        397
480       240                    Zimmermann/Zimmerin EFZ
481       240                                        431

[482 rows x 2 columns]

In [12]:
df.dtypes

0      object
1      object
2      object
3      object
4      object
5      object
6      object
7      object
8      object
9      object
10     object
11     object
12     object
13     object
14     object
15     object
16     object
17     object
18     object
19     object
20     object
21     object
22     object
23     object
24     object
25     object
26     object
27     object
28     object
29     object
        ...
211    object
212    object
213    object
214    object
215    object
216    object
217    object
218    object
219    object
220    object
221    object
222    object
223    object
224    object
225    object
226    object
227    object
228    object
229    object
230    object
231    object
232    object
233    object
234    object
235    object
236    object
237    object
238    object
239    object
240    object
Length: 241, dtype: object

In [7]:
df.shape

(1, 241)

**RESULTAT 1:** Im Lehrstellennachweis LENA gibt es **241** verschiedene Berufe.

In [15]:
df[value].count

NameError: name 'value' is not defined